
package com.grupo01.softwarenominas.capapresentacion;

import javax.swing.UnsupportedLookAndFeelException;

import com.grupo01.softwarenominas.capapresentacion.utils.ConstantesUIContrato;

public class FrmMenu extends javax.swing.JFrame {
    
    int xmouse,ymouse;
    
    public FrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel panelMov = new javax.swing.JPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();

        javax.swing.JButton btnRegistrarContrato = new javax.swing.JButton();
        javax.swing.JButton btnRegistrarNomina = new javax.swing.JButton();
        javax.swing.JButton btnRegistrarTrabajador = new javax.swing.JButton();
        javax.swing.JButton btnRegistrarTrabajador1 = new javax.swing.JButton();

        javax.swing.JLabel jlbContrato = new javax.swing.JLabel();
        javax.swing.JLabel jlbFondo = new javax.swing.JLabel();
        javax.swing.JLabel jlbNomina = new javax.swing.JLabel();
        javax.swing.JLabel jlbNominas = new javax.swing.JLabel();
        javax.swing.JLabel jlbTrabajador = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMov.setOpaque(false);
        panelMov.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMovMouseDragged(evt);
            }
        });
        panelMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMovMousePressed(evt);
            }
        });
        getContentPane().add(panelMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 50));

        btnRegistrarContrato.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarContrato.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarContrato.setText("REGISTRAR CONTRATO");
        btnRegistrarContrato.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarContratoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 210, 50));

        btnRegistrarNomina.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarNomina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarNomina.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarNomina.setText("REGISTRAR NOMINA");
        btnRegistrarNomina.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNominaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, 210, 50));

        btnRegistrarTrabajador.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarTrabajador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTrabajador.setText("REGISTRAR TRABAJADOR");
        btnRegistrarTrabajador.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 210, 50));

        btnRegistrarTrabajador1.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrarTrabajador1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrarTrabajador1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTrabajador1.setText("SALIR");
        btnRegistrarTrabajador1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegistrarTrabajador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrabajador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarTrabajador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 50));

        jlbNomina.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlbNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nomina.png"))); // NOI18N
        getContentPane().add(jlbNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        jlbContrato.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlbContrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contrato.png"))); // NOI18N
        getContentPane().add(jlbContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));

        jlbTrabajador.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jlbTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trabajador.png"))); // NOI18N
        getContentPane().add(jlbTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, -1));

        jlbNominas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jlbNominas.setForeground(new java.awt.Color(255, 255, 255));
        jlbNominas.setText("NOMINAS");
        getContentPane().add(jlbNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoNomina.png"))); // NOI18N
        getContentPane().add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 640));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 370, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNominaActionPerformed
        FrmNomina nomina = new FrmNomina();
        nomina.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarNominaActionPerformed

    private void btnRegistrarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarContratoActionPerformed
        FrmContrato contrato = new FrmContrato();
        contrato.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarContratoActionPerformed

    private void btnRegistrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrabajadorActionPerformed
        FrmTrabajador trabajador = new FrmTrabajador();
        trabajador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrarTrabajadorActionPerformed

    private void btnRegistrarTrabajador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrabajador1ActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnRegistrarTrabajador1ActionPerformed

    private void panelMovMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMovMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xmouse,y - ymouse);
    }//GEN-LAST:event_panelMovMouseDragged

    private void panelMovMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMovMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_panelMovMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    // End of variables declaration//GEN-END:variables
}
